package com.hackathon.notificacao.email.enums;

public enum EventType {
    // HEALTHFACILITY (ADMIN)
    HEALTHFACILITY_CREATED,
    HEALTHFACILITY_UPDATED,
    HEALTHFACILITY_DELETED,

    // HEALTHFACILITY (USER)
    CONSULT_BY_CNES,
    CONSULT_BY_ADDRESS,

    // INVENTORY (ADMIN)
    INVENTORY_CREATED,
    INVENTORY_UPDATED,
    INVENTORY_DELETED,
    INVENTORY_EXPIRED,
    INVENTORY_LOW_STOCK,

    // INVENTORY (BOTH)
    CONSULT_BY_HEALTHFACILITY_NAME,
    CONSULT_BY_VACCINE_NAME,
    CONSULT_BY_HEALTHFACILITY_NAME_AND_VACCINE_NAME,

    // VACCINE (BOTH)
    CONSULT_VACCINE_BY_NAME,
    CONSULT_VACCINE_BY_DISEASE,
    CONSULT_VACCINE_BY_LIFESTAGE,
    CONSULT_VACCINE_BY_AGERANGE
}
